# Generated by Django 2.0.2 on 2018-02-13 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='education',
            name='exerience_values',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='exerience_values',
        ),
        migrations.AddField(
            model_name='education',
            name='degree',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='education',
            name='gpa',
            field=models.TextField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='education',
            name='institution_name',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='education',
            name='location',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='education',
            name='major',
            field=models.CharField(blank=True, max_length=355),
        ),
        migrations.AddField(
            model_name='experience',
            name='description',
            field=models.TextField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='experience',
            name='end_date',
            field=models.CharField(blank=True, max_length=355),
        ),
        migrations.AddField(
            model_name='experience',
            name='location',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='experience',
            name='start_date',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='experience',
            name='title',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
